# Generated by Django 4.1.3 on 2022-11-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antispoofing_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='video_hex_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
