# Generated by Django 4.1.3 on 2022-11-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antispoofing_auth', '0003_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='video',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='video_hex_code',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='video',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='video_hex_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='video_s3_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='video_s3_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
